version: '3'

services:
  minio:
    image: minio/minio:RELEASE.2023-02-10T18-48-39Z
    ports:
      - '9000:9000'
      - '9090:9090'
    volumes:
      - './minio_data:/data'
    env_file:
      - .env
    command: server --console-address ":9090" /data

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: fungjai-zookeeper
    ports:
      - '2181:2181'
      
  kafka:
    image: wurstmeister/kafka
    container_name: fungjai-kafka
    ports:
      - '9092:9092'
    env_file:
      - .env
    depends_on:
      - zookeeper

  webhook:
    image: fungjai-webhook:1.0.8
    container_name: docker-webhook
    ports:
      - "1323:1323"
    env_file:
      - .env
    depends_on:
      - minio

  consumer-kafka:
    image: fungjai-python-consumer:1.0.2
    container_name: python-consumer-kafka
    env_file:
      - .env
    depends_on:
      - webhook

  # minio:
  #   image: minio/minio:RELEASE.2023-02-10T18-48-39Z
  #   ports:
  #     - '9000:9000'
  #     - '9090:9090'
  #   volumes:
  #     - './minio_data:/data'
  #   env_file:
  #     - .env
  #   command: server --console-address ":9090" /data

  # click_server:
  #   image: clickhouse/clickhouse-server:23.1.3.5-alpine
  #   ports:
  #     - "8123:8123"
  #   volumes:
  #     - ./clickhouse_data:/var/lib/clickhouse
  #     - ./init.sql:/docker-entrypoint-initdb.d/init.sql